// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exstysvgvzgdkawbqzje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4c3R5c3ZndnpnZGthd2JxemplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MzYyMTksImV4cCI6MjA1MTQxMjIxOX0.K6jbXata4cpAxfl76z8ir8HEdkajIC5aWzkaqIUoU3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);